[project]
name = "mastho"
dynamic = ["version"]
description = "Tiny Python MAST Client"
readme = "README.md"
authors = [
    { name = "Thomas Vandal", email = "thomas.vandal@umontreal.ca" }
]
requires-python = ">=3.14"
dependencies = ["astroquery", "pandas"]

[dependency-groups]
dev = [
    "ipython",
]

[project.scripts]
mastho = "mastho.cli:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/mastho/_version.py"
